#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Otomasyon")]
	public partial class DataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTbl_Stok(Tbl_Stok instance);
    partial void UpdateTbl_Stok(Tbl_Stok instance);
    partial void DeleteTbl_Stok(Tbl_Stok instance);
    partial void InsertTbl_StokGruplari(Tbl_StokGruplari instance);
    partial void UpdateTbl_StokGruplari(Tbl_StokGruplari instance);
    partial void DeleteTbl_StokGruplari(Tbl_StokGruplari instance);
    partial void InsertTbl_CariGuruplari(Tbl_CariGuruplari instance);
    partial void UpdateTbl_CariGuruplari(Tbl_CariGuruplari instance);
    partial void DeleteTbl_CariGuruplari(Tbl_CariGuruplari instance);
    partial void InsertTBL_Cariler(TBL_Cariler instance);
    partial void UpdateTBL_Cariler(TBL_Cariler instance);
    partial void DeleteTBL_Cariler(TBL_Cariler instance);
    partial void InsertTBL_Kasalar(TBL_Kasalar instance);
    partial void UpdateTBL_Kasalar(TBL_Kasalar instance);
    partial void DeleteTBL_Kasalar(TBL_Kasalar instance);
    partial void InsertTbl_KasaHareketleri(Tbl_KasaHareketleri instance);
    partial void UpdateTbl_KasaHareketleri(Tbl_KasaHareketleri instance);
    partial void DeleteTbl_KasaHareketleri(Tbl_KasaHareketleri instance);
    partial void InsertTbl_CariHareketleri(Tbl_CariHareketleri instance);
    partial void UpdateTbl_CariHareketleri(Tbl_CariHareketleri instance);
    partial void DeleteTbl_CariHareketleri(Tbl_CariHareketleri instance);
    #endregion
		
		public DataBaseDataContext() : 
				base(global::Otomasyon.Properties.Settings.Default.OtomasyonConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Stok> Tbl_Stoks
		{
			get
			{
				return this.GetTable<Tbl_Stok>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_StokGruplari> Tbl_StokGruplaris
		{
			get
			{
				return this.GetTable<Tbl_StokGruplari>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_CariGuruplari> Tbl_CariGuruplaris
		{
			get
			{
				return this.GetTable<Tbl_CariGuruplari>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Cariler> TBL_Carilers
		{
			get
			{
				return this.GetTable<TBL_Cariler>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Kasalar> TBL_Kasalars
		{
			get
			{
				return this.GetTable<TBL_Kasalar>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_KasaHareketleri> Tbl_KasaHareketleris
		{
			get
			{
				return this.GetTable<Tbl_KasaHareketleri>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_CariHareketleri> Tbl_CariHareketleris
		{
			get
			{
				return this.GetTable<Tbl_CariHareketleri>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Stok")]
	public partial class Tbl_Stok : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _StokBarkod;
		
		private string _StokKodu;
		
		private string _StokAdi;
		
		private string _StokBirim;
		
		private System.Nullable<decimal> _StokAlisFiyati;
		
		private System.Nullable<decimal> _StokSatiFiyati;
		
		private System.Nullable<decimal> _StokAlisKdv;
		
		private System.Nullable<decimal> _StokSatisKdv;
		
		private System.Nullable<int> _StokGrupId;
		
		private System.Data.Linq.Binary _StokResim;
		
		private System.Nullable<int> _StokSaveUser;
		
		private System.Nullable<System.DateTime> _StokSaveDate;
		
		private System.Nullable<int> _StokEditUser;
		
		private System.Nullable<System.DateTime> _StokEditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStokBarkodChanging(string value);
    partial void OnStokBarkodChanged();
    partial void OnStokKoduChanging(string value);
    partial void OnStokKoduChanged();
    partial void OnStokAdiChanging(string value);
    partial void OnStokAdiChanged();
    partial void OnStokBirimChanging(string value);
    partial void OnStokBirimChanged();
    partial void OnStokAlisFiyatiChanging(System.Nullable<decimal> value);
    partial void OnStokAlisFiyatiChanged();
    partial void OnStokSatiFiyatiChanging(System.Nullable<decimal> value);
    partial void OnStokSatiFiyatiChanged();
    partial void OnStokAlisKdvChanging(System.Nullable<decimal> value);
    partial void OnStokAlisKdvChanged();
    partial void OnStokSatisKdvChanging(System.Nullable<decimal> value);
    partial void OnStokSatisKdvChanged();
    partial void OnStokGrupIdChanging(System.Nullable<int> value);
    partial void OnStokGrupIdChanged();
    partial void OnStokResimChanging(System.Data.Linq.Binary value);
    partial void OnStokResimChanged();
    partial void OnStokSaveUserChanging(System.Nullable<int> value);
    partial void OnStokSaveUserChanged();
    partial void OnStokSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStokSaveDateChanged();
    partial void OnStokEditUserChanging(System.Nullable<int> value);
    partial void OnStokEditUserChanged();
    partial void OnStokEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStokEditDateChanged();
    #endregion
		
		public Tbl_Stok()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokBarkod", DbType="NVarChar(20)")]
		public string StokBarkod
		{
			get
			{
				return this._StokBarkod;
			}
			set
			{
				if ((this._StokBarkod != value))
				{
					this.OnStokBarkodChanging(value);
					this.SendPropertyChanging();
					this._StokBarkod = value;
					this.SendPropertyChanged("StokBarkod");
					this.OnStokBarkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokKodu", DbType="NVarChar(20)")]
		public string StokKodu
		{
			get
			{
				return this._StokKodu;
			}
			set
			{
				if ((this._StokKodu != value))
				{
					this.OnStokKoduChanging(value);
					this.SendPropertyChanging();
					this._StokKodu = value;
					this.SendPropertyChanged("StokKodu");
					this.OnStokKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokAdi", DbType="NVarChar(50)")]
		public string StokAdi
		{
			get
			{
				return this._StokAdi;
			}
			set
			{
				if ((this._StokAdi != value))
				{
					this.OnStokAdiChanging(value);
					this.SendPropertyChanging();
					this._StokAdi = value;
					this.SendPropertyChanged("StokAdi");
					this.OnStokAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokBirim", DbType="NVarChar(15)")]
		public string StokBirim
		{
			get
			{
				return this._StokBirim;
			}
			set
			{
				if ((this._StokBirim != value))
				{
					this.OnStokBirimChanging(value);
					this.SendPropertyChanging();
					this._StokBirim = value;
					this.SendPropertyChanged("StokBirim");
					this.OnStokBirimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokAlisFiyati", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> StokAlisFiyati
		{
			get
			{
				return this._StokAlisFiyati;
			}
			set
			{
				if ((this._StokAlisFiyati != value))
				{
					this.OnStokAlisFiyatiChanging(value);
					this.SendPropertyChanging();
					this._StokAlisFiyati = value;
					this.SendPropertyChanged("StokAlisFiyati");
					this.OnStokAlisFiyatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokSatiFiyati", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> StokSatiFiyati
		{
			get
			{
				return this._StokSatiFiyati;
			}
			set
			{
				if ((this._StokSatiFiyati != value))
				{
					this.OnStokSatiFiyatiChanging(value);
					this.SendPropertyChanging();
					this._StokSatiFiyati = value;
					this.SendPropertyChanged("StokSatiFiyati");
					this.OnStokSatiFiyatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokAlisKdv", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> StokAlisKdv
		{
			get
			{
				return this._StokAlisKdv;
			}
			set
			{
				if ((this._StokAlisKdv != value))
				{
					this.OnStokAlisKdvChanging(value);
					this.SendPropertyChanging();
					this._StokAlisKdv = value;
					this.SendPropertyChanged("StokAlisKdv");
					this.OnStokAlisKdvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokSatisKdv", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> StokSatisKdv
		{
			get
			{
				return this._StokSatisKdv;
			}
			set
			{
				if ((this._StokSatisKdv != value))
				{
					this.OnStokSatisKdvChanging(value);
					this.SendPropertyChanging();
					this._StokSatisKdv = value;
					this.SendPropertyChanged("StokSatisKdv");
					this.OnStokSatisKdvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokGrupId", DbType="Int")]
		public System.Nullable<int> StokGrupId
		{
			get
			{
				return this._StokGrupId;
			}
			set
			{
				if ((this._StokGrupId != value))
				{
					this.OnStokGrupIdChanging(value);
					this.SendPropertyChanging();
					this._StokGrupId = value;
					this.SendPropertyChanged("StokGrupId");
					this.OnStokGrupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokResim", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary StokResim
		{
			get
			{
				return this._StokResim;
			}
			set
			{
				if ((this._StokResim != value))
				{
					this.OnStokResimChanging(value);
					this.SendPropertyChanging();
					this._StokResim = value;
					this.SendPropertyChanged("StokResim");
					this.OnStokResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokSaveUser", DbType="Int")]
		public System.Nullable<int> StokSaveUser
		{
			get
			{
				return this._StokSaveUser;
			}
			set
			{
				if ((this._StokSaveUser != value))
				{
					this.OnStokSaveUserChanging(value);
					this.SendPropertyChanging();
					this._StokSaveUser = value;
					this.SendPropertyChanged("StokSaveUser");
					this.OnStokSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StokSaveDate
		{
			get
			{
				return this._StokSaveDate;
			}
			set
			{
				if ((this._StokSaveDate != value))
				{
					this.OnStokSaveDateChanging(value);
					this.SendPropertyChanging();
					this._StokSaveDate = value;
					this.SendPropertyChanged("StokSaveDate");
					this.OnStokSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokEditUser", DbType="Int")]
		public System.Nullable<int> StokEditUser
		{
			get
			{
				return this._StokEditUser;
			}
			set
			{
				if ((this._StokEditUser != value))
				{
					this.OnStokEditUserChanging(value);
					this.SendPropertyChanging();
					this._StokEditUser = value;
					this.SendPropertyChanged("StokEditUser");
					this.OnStokEditUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StokEditDate
		{
			get
			{
				return this._StokEditDate;
			}
			set
			{
				if ((this._StokEditDate != value))
				{
					this.OnStokEditDateChanging(value);
					this.SendPropertyChanging();
					this._StokEditDate = value;
					this.SendPropertyChanged("StokEditDate");
					this.OnStokEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_StokGruplari")]
	public partial class Tbl_StokGruplari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _GurupAdi;
		
		private string _GrupKodu;
		
		private System.Nullable<int> _GrupSaveUser;
		
		private System.Nullable<System.DateTime> _GrupSaveDate;
		
		private System.Nullable<int> _GrupEditUser;
		
		private System.Nullable<System.DateTime> _GrupEditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGurupAdiChanging(string value);
    partial void OnGurupAdiChanged();
    partial void OnGrupKoduChanging(string value);
    partial void OnGrupKoduChanged();
    partial void OnGrupSaveUserChanging(System.Nullable<int> value);
    partial void OnGrupSaveUserChanged();
    partial void OnGrupSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGrupSaveDateChanged();
    partial void OnGrupEditUserChanging(System.Nullable<int> value);
    partial void OnGrupEditUserChanged();
    partial void OnGrupEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGrupEditDateChanged();
    #endregion
		
		public Tbl_StokGruplari()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GurupAdi", DbType="NVarChar(50)")]
		public string GurupAdi
		{
			get
			{
				return this._GurupAdi;
			}
			set
			{
				if ((this._GurupAdi != value))
				{
					this.OnGurupAdiChanging(value);
					this.SendPropertyChanging();
					this._GurupAdi = value;
					this.SendPropertyChanged("GurupAdi");
					this.OnGurupAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupKodu", DbType="NVarChar(50)")]
		public string GrupKodu
		{
			get
			{
				return this._GrupKodu;
			}
			set
			{
				if ((this._GrupKodu != value))
				{
					this.OnGrupKoduChanging(value);
					this.SendPropertyChanging();
					this._GrupKodu = value;
					this.SendPropertyChanged("GrupKodu");
					this.OnGrupKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupSaveUser", DbType="Int")]
		public System.Nullable<int> GrupSaveUser
		{
			get
			{
				return this._GrupSaveUser;
			}
			set
			{
				if ((this._GrupSaveUser != value))
				{
					this.OnGrupSaveUserChanging(value);
					this.SendPropertyChanging();
					this._GrupSaveUser = value;
					this.SendPropertyChanged("GrupSaveUser");
					this.OnGrupSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GrupSaveDate
		{
			get
			{
				return this._GrupSaveDate;
			}
			set
			{
				if ((this._GrupSaveDate != value))
				{
					this.OnGrupSaveDateChanging(value);
					this.SendPropertyChanging();
					this._GrupSaveDate = value;
					this.SendPropertyChanged("GrupSaveDate");
					this.OnGrupSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupEditUser", DbType="Int")]
		public System.Nullable<int> GrupEditUser
		{
			get
			{
				return this._GrupEditUser;
			}
			set
			{
				if ((this._GrupEditUser != value))
				{
					this.OnGrupEditUserChanging(value);
					this.SendPropertyChanging();
					this._GrupEditUser = value;
					this.SendPropertyChanged("GrupEditUser");
					this.OnGrupEditUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GrupEditDate
		{
			get
			{
				return this._GrupEditDate;
			}
			set
			{
				if ((this._GrupEditDate != value))
				{
					this.OnGrupEditDateChanging(value);
					this.SendPropertyChanging();
					this._GrupEditDate = value;
					this.SendPropertyChanged("GrupEditDate");
					this.OnGrupEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_CariGuruplaris")]
	public partial class Tbl_CariGuruplari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _GrupAdi;
		
		private string _GrupKodu;
		
		private System.DateTime _SaveDate;
		
		private int _SaveUser;
		
		private System.DateTime _EditDate;
		
		private int _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGrupAdiChanging(string value);
    partial void OnGrupAdiChanged();
    partial void OnGrupKoduChanging(string value);
    partial void OnGrupKoduChanged();
    partial void OnSaveDateChanging(System.DateTime value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(int value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.DateTime value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(int value);
    partial void OnEditUserChanged();
    #endregion
		
		public Tbl_CariGuruplari()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GrupAdi
		{
			get
			{
				return this._GrupAdi;
			}
			set
			{
				if ((this._GrupAdi != value))
				{
					this.OnGrupAdiChanging(value);
					this.SendPropertyChanging();
					this._GrupAdi = value;
					this.SendPropertyChanged("GrupAdi");
					this.OnGrupAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupKodu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GrupKodu
		{
			get
			{
				return this._GrupKodu;
			}
			set
			{
				if ((this._GrupKodu != value))
				{
					this.OnGrupKoduChanging(value);
					this.SendPropertyChanging();
					this._GrupKodu = value;
					this.SendPropertyChanged("GrupKodu");
					this.OnGrupKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime NOT NULL")]
		public System.DateTime SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int NOT NULL")]
		public int SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime NOT NULL")]
		public System.DateTime EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int NOT NULL")]
		public int EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Carilers")]
	public partial class TBL_Cariler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CariKodu;
		
		private string _CariAdi;
		
		private string _VergiDairesi;
		
		private string _VergiNo;
		
		private System.Nullable<int> _GrupId;
		
		private string _Ulke;
		
		private string _Sehir;
		
		private string _Ilce;
		
		private string _Adres;
		
		private string _WebAdresi;
		
		private string _MailInfo;
		
		private string _Yetkili1;
		
		private string _YetkiliEmail;
		
		private string _Yetkili;
		
		private string _YetkiliMail;
		
		private string _Telefon1;
		
		private string _Telefon2;
		
		private string _Fax1;
		
		private string _Fax2;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCariKoduChanging(string value);
    partial void OnCariKoduChanged();
    partial void OnCariAdiChanging(string value);
    partial void OnCariAdiChanged();
    partial void OnVergiDairesiChanging(string value);
    partial void OnVergiDairesiChanged();
    partial void OnVergiNoChanging(string value);
    partial void OnVergiNoChanged();
    partial void OnGrupIdChanging(System.Nullable<int> value);
    partial void OnGrupIdChanged();
    partial void OnUlkeChanging(string value);
    partial void OnUlkeChanged();
    partial void OnSehirChanging(string value);
    partial void OnSehirChanged();
    partial void OnIlceChanging(string value);
    partial void OnIlceChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnWebAdresiChanging(string value);
    partial void OnWebAdresiChanged();
    partial void OnMailInfoChanging(string value);
    partial void OnMailInfoChanged();
    partial void OnYetkili1Changing(string value);
    partial void OnYetkili1Changed();
    partial void OnYetkiliEmailChanging(string value);
    partial void OnYetkiliEmailChanged();
    partial void OnYetkiliChanging(string value);
    partial void OnYetkiliChanged();
    partial void OnYetkiliMailChanging(string value);
    partial void OnYetkiliMailChanged();
    partial void OnTelefon1Changing(string value);
    partial void OnTelefon1Changed();
    partial void OnTelefon2Changing(string value);
    partial void OnTelefon2Changed();
    partial void OnFax1Changing(string value);
    partial void OnFax1Changed();
    partial void OnFax2Changing(string value);
    partial void OnFax2Changed();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public TBL_Cariler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariKodu", DbType="NVarChar(MAX)")]
		public string CariKodu
		{
			get
			{
				return this._CariKodu;
			}
			set
			{
				if ((this._CariKodu != value))
				{
					this.OnCariKoduChanging(value);
					this.SendPropertyChanging();
					this._CariKodu = value;
					this.SendPropertyChanged("CariKodu");
					this.OnCariKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariAdi", DbType="NVarChar(MAX)")]
		public string CariAdi
		{
			get
			{
				return this._CariAdi;
			}
			set
			{
				if ((this._CariAdi != value))
				{
					this.OnCariAdiChanging(value);
					this.SendPropertyChanging();
					this._CariAdi = value;
					this.SendPropertyChanged("CariAdi");
					this.OnCariAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiDairesi", DbType="NVarChar(MAX)")]
		public string VergiDairesi
		{
			get
			{
				return this._VergiDairesi;
			}
			set
			{
				if ((this._VergiDairesi != value))
				{
					this.OnVergiDairesiChanging(value);
					this.SendPropertyChanging();
					this._VergiDairesi = value;
					this.SendPropertyChanged("VergiDairesi");
					this.OnVergiDairesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiNo", DbType="NVarChar(MAX)")]
		public string VergiNo
		{
			get
			{
				return this._VergiNo;
			}
			set
			{
				if ((this._VergiNo != value))
				{
					this.OnVergiNoChanging(value);
					this.SendPropertyChanging();
					this._VergiNo = value;
					this.SendPropertyChanged("VergiNo");
					this.OnVergiNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupId", DbType="Int")]
		public System.Nullable<int> GrupId
		{
			get
			{
				return this._GrupId;
			}
			set
			{
				if ((this._GrupId != value))
				{
					this.OnGrupIdChanging(value);
					this.SendPropertyChanging();
					this._GrupId = value;
					this.SendPropertyChanged("GrupId");
					this.OnGrupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulke", DbType="NVarChar(MAX)")]
		public string Ulke
		{
			get
			{
				return this._Ulke;
			}
			set
			{
				if ((this._Ulke != value))
				{
					this.OnUlkeChanging(value);
					this.SendPropertyChanging();
					this._Ulke = value;
					this.SendPropertyChanged("Ulke");
					this.OnUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sehir", DbType="NVarChar(MAX)")]
		public string Sehir
		{
			get
			{
				return this._Sehir;
			}
			set
			{
				if ((this._Sehir != value))
				{
					this.OnSehirChanging(value);
					this.SendPropertyChanging();
					this._Sehir = value;
					this.SendPropertyChanged("Sehir");
					this.OnSehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilce", DbType="NVarChar(MAX)")]
		public string Ilce
		{
			get
			{
				return this._Ilce;
			}
			set
			{
				if ((this._Ilce != value))
				{
					this.OnIlceChanging(value);
					this.SendPropertyChanging();
					this._Ilce = value;
					this.SendPropertyChanged("Ilce");
					this.OnIlceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebAdresi", DbType="NVarChar(MAX)")]
		public string WebAdresi
		{
			get
			{
				return this._WebAdresi;
			}
			set
			{
				if ((this._WebAdresi != value))
				{
					this.OnWebAdresiChanging(value);
					this.SendPropertyChanging();
					this._WebAdresi = value;
					this.SendPropertyChanged("WebAdresi");
					this.OnWebAdresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailInfo", DbType="NVarChar(MAX)")]
		public string MailInfo
		{
			get
			{
				return this._MailInfo;
			}
			set
			{
				if ((this._MailInfo != value))
				{
					this.OnMailInfoChanging(value);
					this.SendPropertyChanging();
					this._MailInfo = value;
					this.SendPropertyChanged("MailInfo");
					this.OnMailInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yetkili1", DbType="NVarChar(MAX)")]
		public string Yetkili1
		{
			get
			{
				return this._Yetkili1;
			}
			set
			{
				if ((this._Yetkili1 != value))
				{
					this.OnYetkili1Changing(value);
					this.SendPropertyChanging();
					this._Yetkili1 = value;
					this.SendPropertyChanged("Yetkili1");
					this.OnYetkili1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetkiliEmail", DbType="NVarChar(50)")]
		public string YetkiliEmail
		{
			get
			{
				return this._YetkiliEmail;
			}
			set
			{
				if ((this._YetkiliEmail != value))
				{
					this.OnYetkiliEmailChanging(value);
					this.SendPropertyChanging();
					this._YetkiliEmail = value;
					this.SendPropertyChanged("YetkiliEmail");
					this.OnYetkiliEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yetkili", DbType="NVarChar(50)")]
		public string Yetkili
		{
			get
			{
				return this._Yetkili;
			}
			set
			{
				if ((this._Yetkili != value))
				{
					this.OnYetkiliChanging(value);
					this.SendPropertyChanging();
					this._Yetkili = value;
					this.SendPropertyChanged("Yetkili");
					this.OnYetkiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetkiliMail", DbType="NVarChar(50)")]
		public string YetkiliMail
		{
			get
			{
				return this._YetkiliMail;
			}
			set
			{
				if ((this._YetkiliMail != value))
				{
					this.OnYetkiliMailChanging(value);
					this.SendPropertyChanging();
					this._YetkiliMail = value;
					this.SendPropertyChanged("YetkiliMail");
					this.OnYetkiliMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon1", DbType="NVarChar(20)")]
		public string Telefon1
		{
			get
			{
				return this._Telefon1;
			}
			set
			{
				if ((this._Telefon1 != value))
				{
					this.OnTelefon1Changing(value);
					this.SendPropertyChanging();
					this._Telefon1 = value;
					this.SendPropertyChanged("Telefon1");
					this.OnTelefon1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon2", DbType="NVarChar(20)")]
		public string Telefon2
		{
			get
			{
				return this._Telefon2;
			}
			set
			{
				if ((this._Telefon2 != value))
				{
					this.OnTelefon2Changing(value);
					this.SendPropertyChanging();
					this._Telefon2 = value;
					this.SendPropertyChanged("Telefon2");
					this.OnTelefon2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax1", DbType="NVarChar(50)")]
		public string Fax1
		{
			get
			{
				return this._Fax1;
			}
			set
			{
				if ((this._Fax1 != value))
				{
					this.OnFax1Changing(value);
					this.SendPropertyChanging();
					this._Fax1 = value;
					this.SendPropertyChanged("Fax1");
					this.OnFax1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax2", DbType="NVarChar(50)")]
		public string Fax2
		{
			get
			{
				return this._Fax2;
			}
			set
			{
				if ((this._Fax2 != value))
				{
					this.OnFax2Changing(value);
					this.SendPropertyChanging();
					this._Fax2 = value;
					this.SendPropertyChanged("Fax2");
					this.OnFax2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Kasalar")]
	public partial class TBL_Kasalar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KasaKodu;
		
		private string _KasaAdi;
		
		private string _Aciklama;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKasaKoduChanging(string value);
    partial void OnKasaKoduChanged();
    partial void OnKasaAdiChanging(string value);
    partial void OnKasaAdiChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public TBL_Kasalar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KasaKodu", DbType="NVarChar(MAX)")]
		public string KasaKodu
		{
			get
			{
				return this._KasaKodu;
			}
			set
			{
				if ((this._KasaKodu != value))
				{
					this.OnKasaKoduChanging(value);
					this.SendPropertyChanging();
					this._KasaKodu = value;
					this.SendPropertyChanged("KasaKodu");
					this.OnKasaKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KasaAdi", DbType="NVarChar(50)")]
		public string KasaAdi
		{
			get
			{
				return this._KasaAdi;
			}
			set
			{
				if ((this._KasaAdi != value))
				{
					this.OnKasaAdiChanging(value);
					this.SendPropertyChanging();
					this._KasaAdi = value;
					this.SendPropertyChanged("KasaAdi");
					this.OnKasaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(50)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_KasaHareketleri")]
	public partial class Tbl_KasaHareketleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _KasaId;
		
		private string _BelgeNo;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private string _EvrakTuru;
		
		private System.Nullable<int> _EvrakId;
		
		private string _GCKodu;
		
		private System.Nullable<decimal> _Tutar;
		
		private System.Nullable<int> _CariId;
		
		private string _Aciklama;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKasaIdChanging(System.Nullable<int> value);
    partial void OnKasaIdChanged();
    partial void OnBelgeNoChanging(string value);
    partial void OnBelgeNoChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnEvrakTuruChanging(string value);
    partial void OnEvrakTuruChanged();
    partial void OnEvrakIdChanging(System.Nullable<int> value);
    partial void OnEvrakIdChanged();
    partial void OnGCKoduChanging(string value);
    partial void OnGCKoduChanged();
    partial void OnTutarChanging(System.Nullable<decimal> value);
    partial void OnTutarChanged();
    partial void OnCariIdChanging(System.Nullable<int> value);
    partial void OnCariIdChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public Tbl_KasaHareketleri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KasaId", DbType="Int")]
		public System.Nullable<int> KasaId
		{
			get
			{
				return this._KasaId;
			}
			set
			{
				if ((this._KasaId != value))
				{
					this.OnKasaIdChanging(value);
					this.SendPropertyChanging();
					this._KasaId = value;
					this.SendPropertyChanged("KasaId");
					this.OnKasaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BelgeNo", DbType="NVarChar(MAX)")]
		public string BelgeNo
		{
			get
			{
				return this._BelgeNo;
			}
			set
			{
				if ((this._BelgeNo != value))
				{
					this.OnBelgeNoChanging(value);
					this.SendPropertyChanging();
					this._BelgeNo = value;
					this.SendPropertyChanged("BelgeNo");
					this.OnBelgeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakTuru", DbType="NVarChar(50)")]
		public string EvrakTuru
		{
			get
			{
				return this._EvrakTuru;
			}
			set
			{
				if ((this._EvrakTuru != value))
				{
					this.OnEvrakTuruChanging(value);
					this.SendPropertyChanging();
					this._EvrakTuru = value;
					this.SendPropertyChanged("EvrakTuru");
					this.OnEvrakTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakId", DbType="Int")]
		public System.Nullable<int> EvrakId
		{
			get
			{
				return this._EvrakId;
			}
			set
			{
				if ((this._EvrakId != value))
				{
					this.OnEvrakIdChanging(value);
					this.SendPropertyChanging();
					this._EvrakId = value;
					this.SendPropertyChanged("EvrakId");
					this.OnEvrakIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GCKodu", DbType="NVarChar(50)")]
		public string GCKodu
		{
			get
			{
				return this._GCKodu;
			}
			set
			{
				if ((this._GCKodu != value))
				{
					this.OnGCKoduChanging(value);
					this.SendPropertyChanging();
					this._GCKodu = value;
					this.SendPropertyChanged("GCKodu");
					this.OnGCKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariId", DbType="Int")]
		public System.Nullable<int> CariId
		{
			get
			{
				return this._CariId;
			}
			set
			{
				if ((this._CariId != value))
				{
					this.OnCariIdChanging(value);
					this.SendPropertyChanging();
					this._CariId = value;
					this.SendPropertyChanged("CariId");
					this.OnCariIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_CariHareketleri")]
	public partial class Tbl_CariHareketleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _CariId;
		
		private string _EvrakTuru;
		
		private System.Nullable<int> _EvrakId;
		
		private System.Nullable<decimal> _Borc;
		
		private System.Nullable<decimal> _Alacak;
		
		private string _Acıklama;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private string _Tipi;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCariIdChanging(System.Nullable<int> value);
    partial void OnCariIdChanged();
    partial void OnEvrakTuruChanging(string value);
    partial void OnEvrakTuruChanged();
    partial void OnEvrakIdChanging(System.Nullable<int> value);
    partial void OnEvrakIdChanged();
    partial void OnBorcChanging(System.Nullable<decimal> value);
    partial void OnBorcChanged();
    partial void OnAlacakChanging(System.Nullable<decimal> value);
    partial void OnAlacakChanged();
    partial void OnAcıklamaChanging(string value);
    partial void OnAcıklamaChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnTipiChanging(string value);
    partial void OnTipiChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public Tbl_CariHareketleri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariId", DbType="Int")]
		public System.Nullable<int> CariId
		{
			get
			{
				return this._CariId;
			}
			set
			{
				if ((this._CariId != value))
				{
					this.OnCariIdChanging(value);
					this.SendPropertyChanging();
					this._CariId = value;
					this.SendPropertyChanged("CariId");
					this.OnCariIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakTuru", DbType="NVarChar(50)")]
		public string EvrakTuru
		{
			get
			{
				return this._EvrakTuru;
			}
			set
			{
				if ((this._EvrakTuru != value))
				{
					this.OnEvrakTuruChanging(value);
					this.SendPropertyChanging();
					this._EvrakTuru = value;
					this.SendPropertyChanged("EvrakTuru");
					this.OnEvrakTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakId", DbType="Int")]
		public System.Nullable<int> EvrakId
		{
			get
			{
				return this._EvrakId;
			}
			set
			{
				if ((this._EvrakId != value))
				{
					this.OnEvrakIdChanging(value);
					this.SendPropertyChanging();
					this._EvrakId = value;
					this.SendPropertyChanged("EvrakId");
					this.OnEvrakIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borc", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Borc
		{
			get
			{
				return this._Borc;
			}
			set
			{
				if ((this._Borc != value))
				{
					this.OnBorcChanging(value);
					this.SendPropertyChanging();
					this._Borc = value;
					this.SendPropertyChanged("Borc");
					this.OnBorcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alacak", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Alacak
		{
			get
			{
				return this._Alacak;
			}
			set
			{
				if ((this._Alacak != value))
				{
					this.OnAlacakChanging(value);
					this.SendPropertyChanging();
					this._Alacak = value;
					this.SendPropertyChanged("Alacak");
					this.OnAlacakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acıklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Acıklama
		{
			get
			{
				return this._Acıklama;
			}
			set
			{
				if ((this._Acıklama != value))
				{
					this.OnAcıklamaChanging(value);
					this.SendPropertyChanging();
					this._Acıklama = value;
					this.SendPropertyChanged("Acıklama");
					this.OnAcıklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipi", DbType="NVarChar(MAX)")]
		public string Tipi
		{
			get
			{
				return this._Tipi;
			}
			set
			{
				if ((this._Tipi != value))
				{
					this.OnTipiChanging(value);
					this.SendPropertyChanging();
					this._Tipi = value;
					this.SendPropertyChanged("Tipi");
					this.OnTipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
